# The URL the site will be built for
base_url = "https://jproyo.github.io"
compile_sass = true
build_search_index = true
generate_feeds = true
minify_html = true
title = "Tech, Science, Math and more..."

theme = "shadharon"

taxonomies = [
  {name = "tags", feed = true}, # each tag will have its own feed
  {name = "tags"}, # you can have taxonomies with the same name in multiple languages
  {name = "categories", paginate_by = 5, feed = true},  # 5 items per page for a term
  {name = "authors"}, # Basic definition: no feed or pagination
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

[extra]
toc = true
use_cdn = false
search_bar = true
katex_enable = true
katex_auto_render = true
favicon = "/favicons/favicon.ico"

menu = [
    { name = "Articles", url = "/posts", weight = 1, icon = "" },
    { name = "Tags", url = "/tags", weight = 1, icon = "" },
]


#The icons available can be found in "social_icons" in the "static" folder
socials = [
    { name = "github", url = "https://github.com/jproyo", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/juanpabloroyo/", icon = "linkedin" },
    { name = "twitter", url = "https://twitter.com/juanpabloroyo", icon = "twitter" },
    { name = "email", url = "mailto:juanpablo.royo@gmail.com", icon = "email" },
    { name = "rss", url = "/atom.xml", icon = "rss" },
    { name = "reddit", url = "https://www.reddit.com/user/jproyo", icon = "reddit" },
]
